/****** Object:  Table [dbo].[DIM_DATA]    Script Date: 24/06/2021 02:05:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_DATA](
	[SK_DATA] [int] IDENTITY(1,1) NOT NULL,
	[DATA] [datetime] NULL,
 CONSTRAINT [SK_DIMDATA] PRIMARY KEY CLUSTERED 
(
	[SK_DATA] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


