/****** Object:  Table [dbo].[DIM_MARCA]    Script Date: 24/06/2021 02:05:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_MARCA](
	[SK_MARCA] [int] IDENTITY(1,1) NOT NULL,
	[NomeMarca] [nvarchar](255) NOT NULL,
	[Empreendimento] [nvarchar](500) NOT NULL,
 CONSTRAINT [SK_DIMMARCA] PRIMARY KEY CLUSTERED 
(
	[SK_MARCA] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


