/****** Object:  Table [dbo].[DIM_REGIAO]    Script Date: 24/06/2021 02:06:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIM_REGIAO](
	[SK_REGIAO] [int] IDENTITY(1,1) NOT NULL,
	[Regiao] [nvarchar](50) NULL,
 CONSTRAINT [SK_DIMREGIAO] PRIMARY KEY CLUSTERED 
(
	[SK_REGIAO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


