/****** Object:  Table [dbo].[FATO_POSICAOFINANCEIRA]    Script Date: 24/06/2021 02:10:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FATO_POSICAOFINANCEIRA](
	[SK_CLiENTE] [int] NOT NULL,
	[SK_DATA] [int] NOT NULL,
	[SK_FATO] [int] IDENTITY(1,1) NOT NULL,
	[SK_MARCA] [int] NOT NULL,
	[ValorPago] [money] NOT NULL,
	[SaldoDevedor] [money] NOT NULL,
	[VGV] [money] NOT NULL,
 CONSTRAINT [SK_FATO_POSICACAO] PRIMARY KEY CLUSTERED 
(
	[SK_FATO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


